server:
  kitmap-mode: false
  name: "Legend"
  primary-color: "&6" # Supports gradients
  secondary-color: "&e" # Supports gradients
  team-size: 5
  allies: 0
  starting-balance: 250.0
  auto-pickup: true
  ally-damage: false # allies can't hit each other

end:
  entrance: "world_the_end;0.0;58.0;0.0;0.0;0.0;"
  exit: "world;0.0;58.0;0.0;0.0;0.0;"
  exit-end: "world_the_end;5.0;58.0;5.0;0.0;0.0;"
  creepers:
    - "world_the_end;0.0;58.0;0.0;0.0;0.0;"
  players-can-claim: false

nether:
  portals-spawn-on-road: false
  players-can-claim: false

wilderness:
  overworld: 1000

buffer:
  end: 250 # typically gonna be the size of ends worldborder unless you want to enable claiming
  nether: 150
  overworld: 300

team:
  maximum-dtr: 6.0
  regeneration:
    speed: 60 # seconds
    dtr: 0.1 # how much dtr is regened every X seconds
  claim:
    buffer-size: 2 # how many blocks in between claims needed
    maximum-claims: 2 # a player can only extend their claim once from their existing claim
    price-per-block: 0.15
    minimum-size:
      x: 5
      z: 5
    maximum-size:
      x: 50
      z: 50
    wand:
      material: "GOLD_HOE"
      name: '<blend:&3;&b>Claim Wand</>'
      lore:
        - ''
        - '<blend:&3;&b;false>Left Click a Block</>'
        - '&f- &bSelects claim corner #1'
        - ''
        - '<blend:&3;&b;false>Right Click a Block</>'
        - '&f- &dSelects claim corner #2'
        - ' '
        - '<blend:&3;&b;false>Right Click Air</>'
        - '&f- &cCancels current claim process'
        - ''
        - '<blend:&3;&b;false>Crouch + Left Click</>'
        - '&f- &aConfirms the claim purchase'
        - ''
      item-flags:
        - 'HIDE_ENCHANTS'
        - 'HIDE_ATTRIBUTES'
      enchants:
        - 'DURABILITY:10'
      amount: 1