name: Legend
version: '1.0'
main: dev.lbuddyboy.legend.LegendBukkit
api-version: 1.20
depend:
  - Commons
  - DecentHolograms
softdepend:
  - AuctionHouse
  - Events
  - Crates
  - Rollback
  - CombatLogger