server:
  name: "Legend"
  primary-color: "&6" # Supports gradients
  secondary-color: "&e" # Supports gradients
  team-size: 5
  allies: 0
  starting-balance: 250.0
  auto-pickup: true
  ally-damage: false # allies can't hit each other
  deathbans: true
  take-money-on-death: true
  fast-brew: true
  fast-smelt: true
  uhc-mode: false
  disable-swing-sound: false
  disable-swing-delay: false
  disallowed-teams:
    - 'glowstone'
    - 'spawn'
    - 'loothill'
    - 'deathban'
    - 'nigger'
    - 'nigga'
    - 'faggot'
    - 'bean'
    - 'beaner'
    - 'gook'
    - 'chink'

modifiers:
  base-damage: 1.0
  saturation: 1.0
  durability: 1.0

points:
  kill: 5
  death: -5
  koth: 50
  citadel: 150
  dtc: 75
  made-raidable: 25
  went-raidable: -25

kitmap:
  enabled: false
  kill-reward:
    enabled: true
    commands:
      - 'crate give Kill %player% 1'
      - 'eco add %player% 100'
  kill-streaks:
    enabled: false
    goals:
      5:
        name: "<blend:&4;&c>2x Kill Keys</>"
        commands:
          - 'cr give Kill %player% 2'
      3:
        name: "<blend:&4;&c>1x Kill Key</>"
        commands:
          - 'cr give Kill %player% 1'

shop:
  custom-items: {} # this is managed in game

end:
  entrance: "world_the_end;0.0;58.0;0.0;0.0;0.0;"
  exit: "world;0.0;58.0;0.0;0.0;0.0;"
  exit-end: "world_the_end;5.0;58.0;5.0;0.0;0.0;"
  creepers:
    - "world_the_end;0.0;58.0;0.0;0.0;0.0;"
  players-can-claim: false

nether:
  portals-spawn-on-road: false
  players-can-claim: false

wilderness:
  overworld: 1000
  nether: 0
  end: 0

buffer:
  end: 250 # typically gonna be the size of ends worldborder unless you want to enable claiming
  nether: 150
  overworld: 300

team:
  maximum-dtr: 6.0
  regeneration:
    cooldown: "30m" # how long should you be put on dtr regen
    loss: 1.0 # how much DTR is lost upon death
    speed: 60 # seconds
    dtr: 0.1 # how much dtr is regened every X seconds
  claim:
    buffer-size: 2 # how many blocks in between claims needed
    maximum-claims: 2 # a player can only extend their claim once from their existing claim
    price-per-block: 0.15
    minimum-size:
      x: 5
      z: 5
    maximum-size:
      x: 50
      z: 50
    wand:
      material: "BRUSH"
      name: '<blend:&3;&b>Claim Wand</>'
      lore:
        - ''
        - '<blend:&3;&b;false>Left Click a Block</>'
        - '&f- &bSelects claim corner #1'
        - ''
        - '<blend:&3;&b;false>Right Click a Block</>'
        - '&f- &dSelects claim corner #2'
        - ' '
        - '<blend:&3;&b;false>Right Click Air</>'
        - '&f- &cCancels current claim process'
        - ''
        - '<blend:&3;&b;false>Crouch + Left Click</>'
        - '&f- &aConfirms the claim purchase'
        - ''
      item-flags:
        - 'HIDE_ENCHANTS'
        - 'HIDE_ATTRIBUTES'
      enchants:
        - 'DURABILITY:10'
      amount: 1